stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.6-stretch
  before_script:
    - ./create_virtualenv.sh
    - source venv/bin/activate
  script: pytest

synchronize_byproducts:
  stage: deploy
  image: python:3.6-stretch
  before_script:
    - ./create_virtualenv.sh
    - source venv/bin/activate
  script: python main.py --synchronize_byproducts
  only:
    - master
