version: "3"
services:
  python:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
    - 8887:8887

  postgres:
    image: postgres:11.1-alpine
    ports:
     - "5432:5432"

  schemacrawler:
    image: schemacrawler/schemacrawler:v15.05.01
    volumes:
      - ./data/byproducts/relational_diagram:/share
      - ./docker/schemacrawler/schemacrawler_entrypoint.sh:/home/schcrwlr/schemacrawler_entrypoint.sh
      - ./docker/schemacrawler/schemacrawler.config.properties:/home/schcrwlr/schemacrawler.config.properties
    command: /bin/bash ./schemacrawler_entrypoint.sh