version: "3"
services:
  python:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
    - 8888:8888

  postgres:
    image: postgres:11.1-alpine
    ports:
     - 5432:5432

  schemacrawler:
    image: schemacrawler/schemacrawler
    volumes:
      - ./data/diagram:/share
    command: >
      bash -c "echo 'Running schema crawler against PostgreSQL' &&
      /opt/schemacrawler/schemacrawler.sh
      -command=schema
      -infolevel=standard
      -server=postgresql -host=postgres -port=5432 -user=postgres -database=postgres
      -title 'Schema DCIRS'
      -outputformat=pdf -outputfile=/share/schema_postgres.pdf &&
      echo 'Done. Relational diagram has been written in data/diagram'"
